# Mock server configuration for Docker
server:
  port: "8899"

validator:
  # Path to the keypair file (Docker volume mount)
  identity_keypair: "/app/local-test/passive-identity.json"
  running_version: "3.0.0"

# Health endpoint configuration
health:
  # Response status code (200, 500, etc.)
  status_code: 200
  # Response body
  response_body: "ok"
