# Mock server configuration for unhealthy validator
server:
  port: "8899"

validator:
  # Path to the keypair file (relative to this config file or absolute path)
  identity_keypair: "../local-test/active-identity.json"
  running_version: "1.18.0"

# Health endpoint configuration
health:
  # Response status code (200, 500, etc.)
  status_code: 500
  # Response body
  response_body: "unhealthy"
