name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if tag is on master branch
        run: |
          if [[ "${{ github.ref_type }}" != "tag" ]]; then
            echo "Not a tag, skipping release"
            exit 1
          fi

          # Get the commit that the tag points to
          TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref_name }})

          # Check if this commit is on master branch
          if ! git branch -r --contains $TAG_COMMIT | grep -q "origin/master"; then
            echo "Tag ${{ github.ref_name }} is not on master branch, skipping release"
            exit 1
          fi

          echo "Tag ${{ github.ref_name }} is on master branch, proceeding with release"

      - name: Get version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set version file
        run: |
          echo "${{ steps.version.outputs.version }}" > cmd/version.txt

      - name: Build binaries for all platforms
        run: |
          docker compose -f docker-compose.dev.yml up --build build-all

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.tag }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
